export type PickupDate = { id: string; date: string; window: string; soldOut?: boolean };
export type Product = { id:string; slug:string; name:string; description:string; ingredients:string; allergens:string; images:string[]; variants:{id:string;label:string;quantity:number;price:number}[]; soldOut?:boolean; soldOutDates?:string[] };
export const pickupDates: PickupDate[] = [
  { id:"pickup-1", date:"2026-09-12", window:"10:00am–12:00pm" },
  { id:"pickup-2", date:"2026-09-19", window:"10:00am–12:00pm" },
  { id:"pickup-3", date:"2026-09-26", window:"10:00am–12:00pm" },
];
export const products: Product[] = [
  { id:"product-signature", slug:"signature-box", name:"Signature Crumbie", description:"A thick chocolate chip cookie with crisp, golden edges and a soft, tender centre, packed with generous chunks of rich chocolate in every bite.", ingredients:"Choose six or twelve thick, freshly baked cookies, made in small batches and ready to share, gift or keep all to yourself.", allergens:"Contains gluten, dairy, eggs and soy. Made in a kitchen that handles peanuts and tree nuts; cross-contact is possible.", images:["https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1400&q=88","https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1400&q=88"], variants:[{id:"signature-6",label:"Box of 6",quantity:6,price:30},{id:"signature-12",label:"Box of 12",quantity:12,price:55}] },
  { id:"product-seasonal", slug:"seasonal-box", name:"Biscoff Caramel", description:"A thick, golden cookie loaded with rich caramel and finished with a generous Biscoff crumb—soft through the centre, with a gently crisp edge.", ingredients:"Pickup dates close 72 hours before their scheduled start time, orders can be placed up until this time. Pickup is in Ivanhoe, Victoria. Exact address provided in your confirmation email after purchase.", allergens:"Contains gluten, dairy, eggs and soy. Made in a kitchen that handles peanuts and tree nuts; cross-contact is possible.", images:["https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=1400&q=88","https://images.unsplash.com/photo-1598373182133-52452f7691ef?auto=format&fit=crop&w=1400&q=88"], variants:[{id:"seasonal-6",label:"Box of 6",quantity:6,price:32},{id:"seasonal-12",label:"Box of 12",quantity:12,price:59}] },
];
export const sharedKitchenWarning="Club Crumbie handles gluten, dairy, eggs, soy, peanuts and tree nuts. Cross-contact is possible, and we cannot accommodate allergy requests for standard boxes.";
export function isDateClosed(date:PickupDate){const cutoff=new Date(`${date.date}T10:00:00+10:00`).getTime()-72*60*60*1000;return Boolean(date.soldOut)||Date.now()>=cutoff;}
